// 0 => mahkeme
// 1 => savcılık
// 2 => diğer

const mahkeme = { id: 0, name: "Mahkeme" };
const savcilik = { id: 1, name: "Savcılık" };
const diger = { id: 2, name: "Diğer" };
// const genel = { id: 3, name: "Genel" };

exports.InstitutionList = [
  {
    id: 1,
    name: "Eskişehir Adliyesi",
    types: [mahkeme, savcilik, diger],
    status: true,
    isDefault: true,
    katipTitleChartVisible: true,
    infazKorumaTitleChartVisible: false,
    order: 1,
  },
  {
    id: 2,
    name: "Mihalıççık Adliyesi",
    types: [mahkeme, savcilik, diger],
    status: true,
    isDefault: false,
    katipTitleChartVisible: true,
    infazKorumaTitleChartVisible: false,
    order: 2,
  },
  {
    id: 3,
    name: "Beylikova Adliyesi",
    types: [mahkeme, savcilik, diger],
    status: true,
    isDefault: false,
    katipTitleChartVisible: true,
    infazKorumaTitleChartVisible: false,
    order: 3,
  },
  {
    id: 4,
    name: "Çifteler Adliyesi",
    types: [mahkeme, savcilik, diger],
    status: true,
    isDefault: false,
    katipTitleChartVisible: true,
    infazKorumaTitleChartVisible: false,
    order: 4,
  },
  {
    id: 5,
    name: "Sivrihisar Adliyesi",
    types: [mahkeme, savcilik, diger],
    status: true,
    isDefault: false,
    katipTitleChartVisible: true,
    infazKorumaTitleChartVisible: false,
    order: 5,
  },
  {
    id: 6,
    name: "Eskişehir 1 Nolu Açık Ceza İnfaz Kurumu",
    types: [diger],
    status: true,
    isDefault: false,
    katipTitleChartVisible: false,
    infazKorumaTitleChartVisible: true,
    order: 8,
  },
  {
    id: 7,
    name: "Eskişehir 2 Nolu Açık Ceza İnfaz Kurumu",
    types: [diger],
    status: true,
    isDefault: false,
    katipTitleChartVisible: false,
    infazKorumaTitleChartVisible: true,
    order: 9,
  },
  {
    id: 8,
    name: "Eskişehir H Tipi Kapalı Ceza İnfaz Kurumu",
    types: [diger],
    status: true,
    isDefault: false,
    katipTitleChartVisible: false,
    infazKorumaTitleChartVisible: true,
    order: 10,
  },
  {
    id: 9,
    name: "Eskişehir L Tipi Kapalı Ceza İnfaz Kurumu",
    types: [diger],
    status: true,
    isDefault: false,
    katipTitleChartVisible: false,
    infazKorumaTitleChartVisible: true,
    order: 11,
  },
  {
    id: 10,
    name: "Eskişehir Denetimli Serbestlik Müdürlüğü",
    types: [diger],
    status: true,
    isDefault: false,
    katipTitleChartVisible: false,
    infazKorumaTitleChartVisible: true,
    order: 12,
  },
  {
    id: 11,
    name: "Dış Kurum",
    types: [diger],
    status: true,
    isDefault: false,
    katipTitleChartVisible: false,
    infazKorumaTitleChartVisible: false,
    order: 13,
  },
  {
    id: 12,
    name: "İnönü Adliyesi",
    types: [mahkeme, savcilik, diger],
    status: true,
    isDefault: false,
    katipTitleChartVisible: true,
    infazKorumaTitleChartVisible: false,
    order: 6,
  },
];
