exports.PersonAttributeList = [
  {
    id: 1,
    name: "Sicil Numarası",
    csvHeaderName: "sicilNo",
    type: "number",
    required: true,
    desc: "Personel'in sicil numarası, özellik aktarımı için zorunlu.",
  },
  {
    id: 2,
    name: "Personel Adı",
    csvHeaderName: "ad",
    type: "string",
    required: false,
    desc: "Personel'in adı",
  },
  {
    id: 3,
    name: "Personel Soyadı",
    csvHeaderName: "soyad",
    type: "string",
    required: false,
    desc: "Personel'in soyadı",
  },
  {
    id: 4,
    name: "Göreve Başlama Tarihi",
    csvHeaderName: "goreveBaslamaTarihi",
    type: "date",
    required: false,
    desc: "Personel'in göreve başlama tarihi (Format AA.GG.YYYY)",
  },
  {
    id: 5,
    name: "Birime Başlama Tarihi",
    csvHeaderName: "birimeBaslamaTarihi",
    type: "date",
    required: false,
    desc: "Personel'in birime başlama tarihi, hali hazırdaki birime başlama tarihini değiştirir. (Format AA.GG.YYYY)",
  },
  {
    id: 6,
    name: "Açıklama",
    csvHeaderName: "description",
    type: "string",
    required: false,
    desc: "Personel hakkında açıklama",
  },
  {
    id: 7,
    name: "Seviye",
    csvHeaderName: "level",
    type: "number",
    required: false,
    desc: "Personel'in seviyesi Min 1 Max 5",
  },
  {
    id: 8,
    name: "TC Kimlik Numarası",
    csvHeaderName: "tckn",
    type: "number",
    required: false,
    desc: "Personel'in TC Kimlik Numarası",
  },
  {
    id: 9,
    name: "Telefon Numarası",
    csvHeaderName: "phoneNumber",
    type: "number",
    required: false,
    desc: "Personel'in telefon numarası",
  },
  {
    id: 10,
    name: "Doğum Tarihi",
    csvHeaderName: "birthDate",
    type: "date",
    required: false,
    desc: "Personel'in doğum tarihi (Format AA.GG.YYYY)",
  },
  {
    id: 11,
    name: "Kan Grubu",
    csvHeaderName: "bloodType",
    type: "string",
    required: false,
    desc: "Personel'in kan grubu İzin Verilen Değerler: A+, A-, B+, B-, AB+, AB-, 0+, 0-",
  },
  {
    id: 12,
    name: "Klavye",
    csvHeaderName: "keyboardType",
    type: "string",
    required: false,
    desc: "Personel'in klavye türü İzin Verilen Değerler: F, Q",
  },
  {
    id: 13,
    name: "Şehit Gazi Yakını",
    csvHeaderName: "isMartyrRelative",
    type: "boolean",
    required: false,
    desc: "Personel'in şehit gazi yakını olup olmadığı ( 1 = evet, 0 = hayır )",
  },
  {
    id: 14,
    name: "Engelli Durumu",
    csvHeaderName: "isDisabled",
    type: "boolean",
    required: false,
    desc: "Personel'in engelli olup olmadığı ( 1 = evet, 0 = hayır )",
  },
  {
    id: 15,
    name:"Nöbet Tutuyor Mu",
    csvHeaderName:"nobetTutuyorMu",
    type:"boolean",
    required:false,
    desc:"Personel'in nöbet tutup tutmadığı (1 = evet, 0 = hayır ) (Zabit Katibi ve Mübaşir için)"
  }
];
