// type 0 mahkeme, type 1 savcılık, type 2 diğer
exports.UnitTypeList = [
  {
    id: 9001,
    name: "Ağır Ceza Mahkemesi",
    institutionTypeId: 0,
    unitType: "Ceza",
    oncelikSirasi: 1,
  },
  {
    id: 9002,
    name: "Aile Mahkemesi",
    institutionTypeId: 0,
    unitType: "Hukuk",
    oncelikSirasi: 2,
  },
  {
    id: 9003,
    name: "Asliye Ceza Mahkemesi",
    institutionTypeId: 0,
    unitType: "Ceza",
    oncelikSirasi: 3,
  },
  {
    id: 9004,
    name: "Asliye Hukuk Mahkemesi",
    institutionTypeId: 0,
    unitType: "Hukuk",
    oncelikSirasi: 4,
  },
  {
    id: 9005,
    name: "Çocuk Mahkemesi",
    institutionTypeId: 0,
    unitType: "Ceza",
    oncelikSirasi: 5,
  },
  {
    id: 9006,
    name: "İcra Ceza Mahkemesi",
    unitType: "Ceza",
    institutionTypeId: 0,
    oncelikSirasi: 6,
  },
  {
    id: 9007,
    name: "İnfaz Hakimliği",
    unitType: "Ceza",
    institutionTypeId: 0,
    oncelikSirasi: 7,
  },
  {
    id: 9009,
    name: "İş Mahkemesi",
    institutionTypeId: 0,
    unitType: "Hukuk",
    oncelikSirasi: 9,
  },
  {
    id: 9011,
    name: "Sulh Ceza Mahkemesi",
    institutionTypeId: 0,
    unitType: "Ceza",
    oncelikSirasi: 11,
  },
  {
    id: 9012,
    name: "Sulh Hukuk Mahkemesi",
    institutionTypeId: 0,
    unitType: "Hukuk",
    oncelikSirasi: 12,
  },
  {
    id: 9014,
    name: "İdari İşler Müdürlüğü",
    institutionTypeId: 1,
    oncelikSirasi: 14,
  },
  {
    id: 9015,
    name: "Terörle Mücadale Şube Müdürlüğü",
    institutionTypeId: 1,
    oncelikSirasi: 15,
  },
  {
    id: 9016,
    name: "Diğer",
    institutionTypeId: 1,
    oncelikSirasi: 16,
  },
  {
    id: 9017,
    name: "Diğer",
    institutionTypeId: 2,
    oncelikSirasi: 17,
  },
];
