// type 0 mahkeme, type 1 savcılık, type 2 diğer
exports.UnitTypeList = [
  // Mahkeme
  {
    id: 9001,
    name: "Ağır Ceza Mahkemesi",
    institutionTypeId: 0, // Kurum tipi
    unitType: "Ceza", // Birimin tipi, birimlerin sıralanmasında kullanılır.
    oncelikSirasi: 1, // Öncelik sırası, birimlerin sıralanmasında kullanılır.
    gerekenKatipSayisi: 5, // Gereken katip sayısı, eksik katip kontrolü yapılırken kullanılır.
    eksikKatipKontrol: true, // Eksik katip kontrolü yapılacak mı?

    tabloMevcutMu: true, // Personellerin tablo olarak gösterilmesi gerekiyor mu?
    tabloHeaderName: "Ağır Ceza Mahkemeleri",
    baskanGerekliMi: true,
    uyeHakimGerekliMi: true,
    hakimGerekliMi: false,
  },
  {
    id: 9002,
    name: "Aile Mahkemesi",
    institutionTypeId: 0,
    unitType: "Hukuk",
    oncelikSirasi: 2,
    gerekenKatipSayisi: 3,
    eksikKatipKontrol: true,

    tabloMevcutMu: true,
    tabloHeaderName: "Aile Mahkemeleri",
    baskanGerekliMi: false,
    uyeHakimGerekliMi: false,
    hakimGerekliMi: true,
  },
  {
    id: 9003,
    name: "Asliye Ceza Mahkemesi",
    institutionTypeId: 0,
    unitType: "Ceza",
    oncelikSirasi: 3,
    gerekenKatipSayisi: 3,
    eksikKatipKontrol: true,
    tabloMevcutMu: true,
    tabloHeaderName: "Asliye Ceza Mahkemeleri",
    baskanGerekliMi: false,
    uyeHakimGerekliMi: false,
    hakimGerekliMi: true,
  },
  {
    id: 9004,
    name: "Asliye Hukuk Mahkemesi",
    institutionTypeId: 0,
    unitType: "Hukuk",
    oncelikSirasi: 4,
    gerekenKatipSayisi: 3,
    eksikKatipKontrol: true,

    tabloMevcutMu: true,
    tabloHeaderName: "Asliye Hukuk Mahkemeleri",
    baskanGerekliMi: false,
    uyeHakimGerekliMi: false,
    hakimGerekliMi: true,
  },
  {
    id: 9005,
    name: "Çocuk Mahkemesi",
    institutionTypeId: 0,
    unitType: "Ceza",
    oncelikSirasi: 5,
    gerekenKatipSayisi: 3,
    eksikKatipKontrol: true,
    tabloMevcutMu: true,
    tabloHeaderName: "Çocuk Mahkemeleri",
    baskanGerekliMi: false,
    uyeHakimGerekliMi: false,
    hakimGerekliMi: true,
  },
  {
    id: 9006,
    name: "İcra Mahkemesi",
    unitType: "Hukuk",
    institutionTypeId: 0,
    oncelikSirasi: 6,
    gerekenKatipSayisi: 3,
    eksikKatipKontrol: true,
    tabloMevcutMu: true,
    tabloHeaderName: "İcra Mahkemeleri",
    baskanGerekliMi: false,
    uyeHakimGerekliMi: false,
    hakimGerekliMi: true,
  },
  {
    id: 9007,
    name: "İnfaz Hakimliği",
    unitType: "Ceza",
    institutionTypeId: 0,
    oncelikSirasi: 7,
    gerekenKatipSayisi: 3,
    eksikKatipKontrol: true,
    tabloMevcutMu: true,
    tabloHeaderName: "İnfaz Hakimliği",
    baskanGerekliMi: false,
    uyeHakimGerekliMi: false,
    hakimGerekliMi: true,
  },
  {
    id: 9009,
    name: "İş Mahkemesi",
    institutionTypeId: 0,
    unitType: "Hukuk",
    oncelikSirasi: 9,
    gerekenKatipSayisi: 3,
    eksikKatipKontrol: true,
    tabloMevcutMu: true,
    tabloHeaderName: "İş Mahkemeleri",
    baskanGerekliMi: false,
    uyeHakimGerekliMi: false,
    hakimGerekliMi: true,
  },
  {
    id: 9011,
    name: "Sulh Ceza Hakimliği",
    institutionTypeId: 0,
    unitType: "Ceza",
    oncelikSirasi: 11,
    gerekenKatipSayisi: 3,
    eksikKatipKontrol: true,
    tabloMevcutMu: true,
    tabloHeaderName: "Sulh Ceza Mahkemeleri",
    baskanGerekliMi: false,
    uyeHakimGerekliMi: false,
    hakimGerekliMi: true,
  },
  {
    id: 9012,
    name: "Sulh Hukuk Mahkemesi",
    institutionTypeId: 0,
    unitType: "Hukuk",
    oncelikSirasi: 12,
    gerekenKatipSayisi: 3,
    eksikKatipKontrol: true,
    tabloMevcutMu: true,
    tabloHeaderName: "Sulh Hukuk Mahkemeleri",
    baskanGerekliMi: false,
    uyeHakimGerekliMi: false,
    hakimGerekliMi: true,
  },
  {
    id: 9013,
    name: "Tüketici Mahkemesi",
    institutionTypeId: 0,
    unitType: "Hukuk",
    oncelikSirasi: 13,
    gerekenKatipSayisi: 3,
    eksikKatipKontrol: true,
    tabloMevcutMu: true,
    tabloHeaderName: "Aile Mahkemeleri",
    baskanGerekliMi: false,
    uyeHakimGerekliMi: false,
    hakimGerekliMi: true,
  },
  {
    id: 9014,
    name: "Asliye Ticaret Mahkemesi",
    institutionTypeId: 0,
    unitType: "Hukuk",
    oncelikSirasi: 14,
    gerekenKatipSayisi: 3,
    eksikKatipKontrol: true,
    tabloMevcutMu: true,
    tabloHeaderName: "Asliye Ticaret Mahkemeleri",
    baskanGerekliMi: false,
    uyeHakimGerekliMi: false,
    hakimGerekliMi: true,
  },

  {
    id: 9030,
    name: "Kadastro Mahkemesi",
    institutionTypeId: 0,
    unitType: "Hukuk",
    oncelikSirasi: 15,
    gerekenKatipSayisi: 3,
    eksikKatipKontrol: true,
    tabloMevcutMu: true,
    tabloHeaderName: "Kadastro Mahkemeleri",
    baskanGerekliMi: false,
    uyeHakimGerekliMi: false,
    hakimGerekliMi: true,
  },

  // SAVCILIK
  {
    id: 9016,
    name: "Cumhuriyet Başsavcılığı",
    institutionTypeId: 1,
    oncelikSirasi: 16,
    eksikKatipKontrol: false,
    tabloMevcutMu: false,
  },

  // Diğer
  {
    id: 9017,
    name: "Genel",
    institutionTypeId: 2,
    oncelikSirasi: 17,
    eksikKatipKontrol: false,
  },
];
